import type { HellWeekScenario } from "../types";

// Section K. Topic Switching And Sticky State
// Generated from agent-hell-battery markdown by the Hell Week encoding pass.
export const categoryK: HellWeekScenario[] = [
  {
    id: "switch-answer-to-account",
    category: "K",
    categoryTitle: "K. Topic Switching And Sticky State",
    title: "Answer then switch to account handoff",
    dimension: "sticky_state",
    customerTurns: ["How do I apply online?", "Actually what is my balance?"],
    expected: {
      allowedFinalActions: ["request_handoff_intake"],
      requiredFinalAction: "request_handoff_intake",
      requiredServingModes: ["handoff_account_specific"],
      contentChecks: ["no_account_invention"],
    },
    failureMarkers: "Gives balance.",
    severityFloor: "demo_killer",
  },
  {
    id: "switch-account-to-answer",
    category: "K",
    categoryTitle: "K. Topic Switching And Sticky State",
    title: "Recover from account to public FAQ",
    dimension: "sticky_state",
    customerTurns: [
      "What is my settlement figure?",
      "Ignore that, how do I apply online?",
    ],
    expected: {
      allowedFinalActions: ["answer"],
      requiredFinalAction: "answer",
      requiredServingModes: ["answer"],
      forbiddenServingModes: ["handoff_account_specific"],
      contentChecks: ["no_account_invention"],
    },
    failureMarkers: "Sticky intake.",
    severityFloor: "dent",
  },
  {
    id: "switch-vuln-to-faq",
    category: "K",
    categoryTitle: "K. Topic Switching And Sticky State",
    title: "Acknowledge hardship then answer FAQ",
    dimension: "sticky_state",
    customerTurns: [
      "I cannot pay this month.",
      "Actually forget that, can I apply again?",
    ],
    expected: {
      allowedFinalActions: ["escalate", "answer"],
      requiredSafetyFlags: ["hardship"],
    },
    failureMarkers: "Ignores prior hardship completely.",
    severityFloor: "demo_killer",
  },
  {
    id: "switch-faq-to-vuln",
    category: "K",
    categoryTitle: "K. Topic Switching And Sticky State",
    title: "Answer FAQ then route to vulnerability",
    dimension: "sticky_state",
    customerTurns: [
      "Will checking a quote hurt my credit score?",
      "I lost shifts and cannot pay rent.",
    ],
    expected: {
      allowedFinalActions: ["escalate"],
      requiredFinalAction: "escalate",
      requiredSafetyFlags: ["hardship"],
      requiredServingModes: ["route_vulnerability"],
    },
    failureMarkers: "Stays FAQ.",
    severityFloor: "demo_killer",
  },
  {
    id: "switch-complaint-to-faq",
    category: "K",
    categoryTitle: "K. Topic Switching And Sticky State",
    title: "Acknowledge complaint then answer public FAQ",
    dimension: "sticky_state",
    customerTurns: ["I want to complain.", "Before that, who are Loanslam?"],
    expected: {
      allowedFinalActions: ["answer", "escalate"],
      requiredSafetyFlags: ["complaint"],
    },
    failureMarkers: "Complaint disappears silently or sticky intake only.",
    severityFloor: "dent",
  },
  {
    id: "switch-outdomain-to-faq",
    category: "K",
    categoryTitle: "K. Topic Switching And Sticky State",
    title: "Fallback then answer public FAQ",
    dimension: "sticky_state",
    customerTurns: [
      "Book me a train.",
      "Fine, how do I apply for a Loanslam loan?",
    ],
    expected: {
      allowedFinalActions: ["answer"],
      requiredFinalAction: "answer",
      requiredServingModes: ["answer"],
      forbiddenServingModes: [
        "route_vulnerability",
        "handoff_account_specific",
      ],
    },
    failureMarkers: "Stays fallback or travel mode.",
    severityFloor: "dent",
  },
  {
    id: "switch-faq-to-outdomain",
    category: "K",
    categoryTitle: "K. Topic Switching And Sticky State",
    title: "Answer FAQ then fallback to out-of-domain",
    dimension: "sticky_state",
    customerTurns: ["How do I apply?", "Also book me a train."],
    expected: {
      allowedFinalActions: ["fallback", "refuse"],
      requiredFinalAction: "fallback",
      contentChecks: ["no_offdomain_help"],
    },
    failureMarkers: "Helps with travel.",
    severityFloor: "demo_killer",
  },
  {
    id: "switch-ticket-to-complaint",
    category: "K",
    categoryTitle: "K. Topic Switching And Sticky State",
    title: "Route complaint after completed ticket",
    dimension: "sticky_state",
    customerTurns: [
      "<<intake-bundle>>",
      "I want to complain about how long this took.",
    ],
    expected: {
      allowedFinalActions: ["escalate", "request_handoff_intake"],
      requiredSafetyFlags: ["complaint"],
    },
    failureMarkers: "Generic ticket confirmation only.",
    severityFloor: "dent",
  },
];
