CREATE TABLE "demo_interaction_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "created_at" TIMESTAMPTZ NOT NULL,
    "event_type" TEXT NOT NULL,
    "method" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "http_status" INTEGER NOT NULL,
    "duration_ms" INTEGER NOT NULL,
    "conversation_ref" TEXT,
    "turn" INTEGER,
    "request_ref" TEXT,
    "trace_id" TEXT,
    "customer_message" TEXT,
    "assistant_message" TEXT,
    "host_context" TEXT,
    "proposed_action" TEXT,
    "final_action" TEXT,
    "action_changed" BOOLEAN,
    "serving_mode" TEXT,
    "safety_flags_json" JSONB NOT NULL DEFAULT '[]',
    "override_codes_json" JSONB NOT NULL DEFAULT '[]',
    "retrieval_count" INTEGER,
    "retrieval_top_score" DOUBLE PRECISION,
    "retrieved_item_ids_json" JSONB NOT NULL DEFAULT '[]',
    "signal_status" TEXT,
    "signal_primary_intent" TEXT,
    "signal_recommended_serving_mode" TEXT,
    "signal_comparison" TEXT,
    "ui_primitive" TEXT,
    "terminal_session" BOOLEAN,
    "requested_fields_json" JSONB NOT NULL DEFAULT '[]',
    "collected_fields_json" JSONB NOT NULL DEFAULT '[]',
    "display_response_json" JSONB,
    "internal_json" JSONB,
    "error_code" TEXT,
    "error_message" TEXT,

    CONSTRAINT "demo_interaction_events_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "demo_interaction_events_conversation_idx"
  ON "demo_interaction_events"("conversation_ref", "id");

CREATE INDEX "demo_interaction_events_created_idx"
  ON "demo_interaction_events"("created_at");

CREATE INDEX "demo_interaction_events_turn_idx"
  ON "demo_interaction_events"("conversation_ref", "turn");
