CREATE TABLE "hell_week_runs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "run_id" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "generated_at" TIMESTAMPTZ NOT NULL,
    "profile" TEXT NOT NULL,
    "planner_json" JSONB NOT NULL,
    "signal_extractor_json" JSONB NOT NULL,
    "policy_version" TEXT NOT NULL,
    "judged" BOOLEAN NOT NULL,
    "duration_ms" INTEGER NOT NULL,
    "verdict" TEXT NOT NULL,
    "headline" TEXT NOT NULL,
    "totals_json" JSONB NOT NULL,
    "safety_floor_json" JSONB NOT NULL,
    "deflection_json" JSONB NOT NULL,
    "routing_precision_json" JSONB NOT NULL,
    "ux_quality_json" JSONB NOT NULL,
    "categories_json" JSONB NOT NULL,
    "dimensions_json" JSONB NOT NULL,
    "severity_counts_json" JSONB NOT NULL,
    "triage_counts_json" JSONB NOT NULL,
    "top_risks_json" JSONB NOT NULL,

    CONSTRAINT "hell_week_runs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "hell_week_scenarios" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "hell_week_run_id" BIGINT NOT NULL,
    "scenario_id" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "conversation_ref" TEXT NOT NULL,
    "duration_ms" INTEGER NOT NULL,
    "error" TEXT,
    "category" TEXT NOT NULL,
    "category_title" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "dimension" TEXT NOT NULL,
    "customer_turns_json" JSONB NOT NULL,
    "expected_json" JSONB NOT NULL,
    "failure_markers" TEXT NOT NULL,
    "watch" TEXT,
    "severity_floor" TEXT NOT NULL,
    "scenario_json" JSONB NOT NULL,

    CONSTRAINT "hell_week_scenarios_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "hell_week_turns" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "hell_week_run_id" BIGINT NOT NULL,
    "hell_week_scenario_id" BIGINT NOT NULL,
    "turn_index" INTEGER NOT NULL,
    "user_message" TEXT NOT NULL,
    "bot_message" TEXT NOT NULL,
    "final_action" TEXT NOT NULL,
    "proposed_action" TEXT NOT NULL,
    "selected_serving_mode" TEXT,
    "effective_serving_mode" TEXT,
    "route_for_scoring" TEXT,
    "selected_route_reason" TEXT,
    "safety_flags_json" JSONB NOT NULL,
    "validator_override_codes_json" JSONB NOT NULL,
    "retrieved_json" JSONB NOT NULL,
    "ui_primitive" TEXT NOT NULL,
    "signal_status" TEXT,
    "signal_primary_intent" TEXT,
    "signal_recommended_mode" TEXT,
    "signal_negated_or_corrected" BOOLEAN,
    "signal_comparison_status" TEXT,
    "signal_latency_ms" INTEGER,
    "turn_json" JSONB NOT NULL,

    CONSTRAINT "hell_week_turns_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "hell_week_grades" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "hell_week_run_id" BIGINT NOT NULL,
    "hell_week_scenario_id" BIGINT NOT NULL,
    "scenario_id" TEXT NOT NULL,
    "pass" BOOLEAN NOT NULL,
    "severity" TEXT NOT NULL,
    "grader_source" TEXT NOT NULL,
    "hard_floor_triggered" BOOLEAN NOT NULL,
    "ux_score" DOUBLE PRECISION,
    "rationale" TEXT NOT NULL,
    "triage_labels_json" JSONB NOT NULL,
    "deterministic_json" JSONB NOT NULL,
    "judge_json" JSONB,
    "grade_json" JSONB NOT NULL,

    CONSTRAINT "hell_week_grades_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "hell_week_runs_run_id_key"
  ON "hell_week_runs"("run_id");

CREATE INDEX "hell_week_runs_generated_idx"
  ON "hell_week_runs"("generated_at");

CREATE INDEX "hell_week_runs_profile_generated_idx"
  ON "hell_week_runs"("profile", "generated_at");

CREATE UNIQUE INDEX "hell_week_scenarios_run_scenario_key"
  ON "hell_week_scenarios"("hell_week_run_id", "scenario_id");

CREATE INDEX "hell_week_scenarios_run_idx"
  ON "hell_week_scenarios"("hell_week_run_id");

CREATE INDEX "hell_week_scenarios_scenario_idx"
  ON "hell_week_scenarios"("scenario_id");

CREATE UNIQUE INDEX "hell_week_turns_scenario_turn_key"
  ON "hell_week_turns"("hell_week_scenario_id", "turn_index");

CREATE INDEX "hell_week_turns_run_idx"
  ON "hell_week_turns"("hell_week_run_id");

CREATE INDEX "hell_week_turns_scenario_idx"
  ON "hell_week_turns"("hell_week_scenario_id");

CREATE UNIQUE INDEX "hell_week_grades_run_scenario_key"
  ON "hell_week_grades"("hell_week_run_id", "scenario_id");

CREATE INDEX "hell_week_grades_run_idx"
  ON "hell_week_grades"("hell_week_run_id");

CREATE INDEX "hell_week_grades_scenario_idx"
  ON "hell_week_grades"("hell_week_scenario_id");

CREATE INDEX "hell_week_grades_pass_severity_idx"
  ON "hell_week_grades"("pass", "severity");

ALTER TABLE "hell_week_scenarios"
  ADD CONSTRAINT "hell_week_scenarios_run_fkey"
  FOREIGN KEY ("hell_week_run_id")
  REFERENCES "hell_week_runs"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE "hell_week_turns"
  ADD CONSTRAINT "hell_week_turns_run_fkey"
  FOREIGN KEY ("hell_week_run_id")
  REFERENCES "hell_week_runs"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE "hell_week_turns"
  ADD CONSTRAINT "hell_week_turns_scenario_fkey"
  FOREIGN KEY ("hell_week_scenario_id")
  REFERENCES "hell_week_scenarios"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE "hell_week_grades"
  ADD CONSTRAINT "hell_week_grades_run_fkey"
  FOREIGN KEY ("hell_week_run_id")
  REFERENCES "hell_week_runs"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE "hell_week_grades"
  ADD CONSTRAINT "hell_week_grades_scenario_fkey"
  FOREIGN KEY ("hell_week_scenario_id")
  REFERENCES "hell_week_scenarios"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;
