CREATE TABLE "hell_week_run_sets" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "set_id" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "generated_at" TIMESTAMPTZ NOT NULL,
    "report_type" TEXT NOT NULL DEFAULT 'stability',
    "profile" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "run_count" INTEGER NOT NULL,
    "scenario_count" INTEGER NOT NULL,
    "scenario_set_changed" BOOLEAN NOT NULL,
    "stable_pass_count" INTEGER NOT NULL,
    "stable_failure_count" INTEGER NOT NULL,
    "recurring_failure_count" INTEGER NOT NULL,
    "one_off_failure_count" INTEGER NOT NULL,
    "mixed_count" INTEGER NOT NULL,
    "summary_json" JSONB NOT NULL,
    "report_json" JSONB NOT NULL,

    CONSTRAINT "hell_week_run_sets_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "hell_week_run_set_members" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "hell_week_run_set_id" BIGINT NOT NULL,
    "hell_week_run_id" BIGINT NOT NULL,
    "position" INTEGER NOT NULL,
    "role" TEXT NOT NULL,

    CONSTRAINT "hell_week_run_set_members_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "hell_week_run_set_scenarios" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "hell_week_run_set_id" BIGINT NOT NULL,
    "scenario_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "dimension" TEXT NOT NULL,
    "pass_count" INTEGER NOT NULL,
    "fail_count" INTEGER NOT NULL,
    "missing_count" INTEGER NOT NULL,
    "worst_severity" TEXT NOT NULL,
    "classification" TEXT NOT NULL,
    "severity_counts_json" JSONB NOT NULL,
    "triage_labels_json" JSONB NOT NULL,
    "outcomes_json" JSONB NOT NULL,
    "scenario_json" JSONB NOT NULL,

    CONSTRAINT "hell_week_run_set_scenarios_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "hell_week_run_set_pairwise_comparisons" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "hell_week_run_set_id" BIGINT NOT NULL,
    "baseline_hell_week_run_id" BIGINT NOT NULL,
    "candidate_hell_week_run_id" BIGINT NOT NULL,
    "baseline_position" INTEGER NOT NULL,
    "candidate_position" INTEGER NOT NULL,
    "comparison_json" JSONB NOT NULL,

    CONSTRAINT "hell_week_run_set_pairwise_comparisons_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "hell_week_run_sets_set_id_key"
  ON "hell_week_run_sets"("set_id");

CREATE INDEX "hell_week_run_sets_generated_idx"
  ON "hell_week_run_sets"("generated_at");

CREATE INDEX "hell_week_run_sets_profile_generated_idx"
  ON "hell_week_run_sets"("profile", "generated_at");

CREATE UNIQUE INDEX "hell_week_run_set_members_position_key"
  ON "hell_week_run_set_members"("hell_week_run_set_id", "position");

CREATE UNIQUE INDEX "hell_week_run_set_members_run_key"
  ON "hell_week_run_set_members"("hell_week_run_set_id", "hell_week_run_id");

CREATE INDEX "hell_week_run_set_members_set_idx"
  ON "hell_week_run_set_members"("hell_week_run_set_id");

CREATE INDEX "hell_week_run_set_members_run_idx"
  ON "hell_week_run_set_members"("hell_week_run_id");

CREATE UNIQUE INDEX "hell_week_run_set_scenarios_key"
  ON "hell_week_run_set_scenarios"("hell_week_run_set_id", "scenario_id");

CREATE INDEX "hell_week_run_set_scenarios_set_idx"
  ON "hell_week_run_set_scenarios"("hell_week_run_set_id");

CREATE INDEX "hell_week_run_set_scenarios_class_idx"
  ON "hell_week_run_set_scenarios"("classification");

CREATE INDEX "hell_week_run_set_scenarios_scenario_idx"
  ON "hell_week_run_set_scenarios"("scenario_id");

CREATE UNIQUE INDEX "hell_week_run_set_pairwise_position_key"
  ON "hell_week_run_set_pairwise_comparisons"("hell_week_run_set_id", "baseline_position", "candidate_position");

CREATE INDEX "hell_week_run_set_pairwise_set_idx"
  ON "hell_week_run_set_pairwise_comparisons"("hell_week_run_set_id");

CREATE INDEX "hell_week_run_set_pairwise_baseline_idx"
  ON "hell_week_run_set_pairwise_comparisons"("baseline_hell_week_run_id");

CREATE INDEX "hell_week_run_set_pairwise_candidate_idx"
  ON "hell_week_run_set_pairwise_comparisons"("candidate_hell_week_run_id");

ALTER TABLE "hell_week_run_set_members"
  ADD CONSTRAINT "hell_week_run_set_members_set_fkey"
  FOREIGN KEY ("hell_week_run_set_id")
  REFERENCES "hell_week_run_sets"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE "hell_week_run_set_members"
  ADD CONSTRAINT "hell_week_run_set_members_run_fkey"
  FOREIGN KEY ("hell_week_run_id")
  REFERENCES "hell_week_runs"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE "hell_week_run_set_scenarios"
  ADD CONSTRAINT "hell_week_run_set_scenarios_set_fkey"
  FOREIGN KEY ("hell_week_run_set_id")
  REFERENCES "hell_week_run_sets"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE "hell_week_run_set_pairwise_comparisons"
  ADD CONSTRAINT "hell_week_run_set_pairwise_set_fkey"
  FOREIGN KEY ("hell_week_run_set_id")
  REFERENCES "hell_week_run_sets"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE "hell_week_run_set_pairwise_comparisons"
  ADD CONSTRAINT "hell_week_run_set_pairwise_baseline_fkey"
  FOREIGN KEY ("baseline_hell_week_run_id")
  REFERENCES "hell_week_runs"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE "hell_week_run_set_pairwise_comparisons"
  ADD CONSTRAINT "hell_week_run_set_pairwise_candidate_fkey"
  FOREIGN KEY ("candidate_hell_week_run_id")
  REFERENCES "hell_week_runs"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;
