import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { basename, resolve } from "node:path";

import prettier from "prettier";

import { chips, page, reportHref } from "./html";
import { loadReportManifest, type ReportEntry } from "./manifest";
import { escapeHtml, renderMarkdown } from "./markdown";

export interface BuildReportsOptions {
  root: string;
  check?: boolean;
}

export async function buildReports(options: BuildReportsOptions): Promise<void> {
  const root = options.root;
  const manifest = loadReportManifest(root);
  const reports = manifest.reports;
  const outDir = resolve(root, "packages/review-host/public/reports");
  mkdirSync(outDir, { recursive: true });

  const outputs = new Map<string, string>();
  for (const report of reports) {
    if (report.source.type === "markdown") {
      outputs.set(
        `${report.id}.html`,
        await canonical(renderReportPage(root, report)),
      );
    }
  }
  outputs.set("index.html", await canonical(renderIndex(reports)));

  const staticFiles = new Set(
    reports
      .filter((report) => report.source.type === "static-html")
      .map((report) => basename(report.source.path)),
  );

  const drift: string[] = [];
  for (const [name, content] of outputs) {
    const target = resolve(outDir, name);
    const current = existsSync(target) ? readFileSync(target, "utf8") : null;
    if (current === content) continue;
    if (options.check) {
      drift.push(name);
    } else {
      writeFileSync(target, content);
      console.log(`wrote ${name}`);
    }
  }

  const known = new Set([...outputs.keys(), ...staticFiles]);
  const unmanifested = readdirSync(outDir).filter(
    (file) => file.endsWith(".html") && !known.has(file),
  );
  if (unmanifested.length) {
    throw new Error(
      `unmanifested public report HTML would be served: ${unmanifested.join(
        ", ",
      )}. List it in packages/review-host/reports-manifest.json or delete it.`,
    );
  }

  if (options.check) {
    if (drift.length) {
      throw new Error(
        `stale /reports pages (run \`just reports-build\`): ${drift.join(", ")}`,
      );
    }
    console.log("reports up to date");
    return;
  }

  console.log(
    `reports: ${reports.length} listed, ${outputs.size - 1} rendered, index regenerated`,
  );
}

function renderReportPage(root: string, report: ReportEntry): string {
  const body = renderMarkdown(readFileSync(resolve(root, report.source.path), "utf8"));
  return page(
    `${report.title} — LoanSlam evidence`,
    [
      "<header>",
      '<p class="kicker"><a href="./">LoanSlam · Evidence reports</a></p>',
      `<h1>${escapeHtml(report.title)}</h1>`,
      `<p class="meta">${escapeHtml(report.date)} · ${escapeHtml(report.campaign)}</p>`,
      `<p class="chips">${chips(report)}</p>`,
      "</header>",
      `<article>\n${body}\n</article>`,
      "<footer>Sanitized summary. Generated from the publish manifest; the full run data stays internal.</footer>",
    ].join("\n"),
  );
}

function renderIndex(reports: ReportEntry[]): string {
  const sorted = [...reports].sort((a, b) => b.date.localeCompare(a.date));
  const hero = sorted[0];
  if (!hero) throw new Error("manifest has no reports");

  const groups = new Map<string, ReportEntry[]>();
  for (const report of sorted) {
    groups.set(report.campaign, [...(groups.get(report.campaign) ?? []), report]);
  }

  const entry = (report: ReportEntry) =>
    [
      "<li>",
      `<a href="${reportHref(report)}">${escapeHtml(report.title)}`,
      `<span>${escapeHtml(report.date)} — ${escapeHtml(report.summary)}</span>`,
      "</a>",
      "</li>",
    ].join("");

  const groupsHtml = [...groups.entries()]
    .map(
      ([campaign, entries]) =>
        `<h2>${escapeHtml(campaign)}</h2>\n<ul class="record">${entries.map(entry).join("\n")}</ul>`,
    )
    .join("\n");

  return page(
    "LoanSlam evidence reports",
    [
      "<header>",
      '<p class="kicker">LoanSlam</p>',
      "<h1>Evidence reports</h1>",
      "<p>Sanitized report views from the testing record: Hell Week gauntlets, adversarial probes, audits, and reviews across the product's evolution. These pages are generated summaries, not raw traces, run JSON, or lab session dumps.</p>",
      "</header>",
      '<section class="hero">',
      '<p class="kicker">Latest</p>',
      `<h2><a href="${reportHref(hero)}">${escapeHtml(hero.title)}</a></h2>`,
      `<p class="meta">${escapeHtml(hero.date)} · ${escapeHtml(hero.campaign)}</p>`,
      `<p>${escapeHtml(hero.summary)}</p>`,
      `<p class="chips">${chips(hero)}</p>`,
      "</section>",
      `<h2 style="font-size:1.05rem;color:#5f6b76;">Full record — ${reports.length} reports</h2>`,
      groupsHtml,
      "<footer>Regenerated by <code>just reports-build</code> from the publish manifest.</footer>",
    ].join("\n"),
  );
}

async function canonical(html: string): Promise<string> {
  return prettier.format(html, { parser: "html" });
}
