import { basename } from "node:path";

import type { ReportEntry } from "./manifest";
import { escapeHtml } from "./markdown";

export const reportCss = `
:root { color: #1c1f23; background: #ffffff; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
body { margin: 0; }
main { max-width: 780px; margin: 0 auto; padding: 48px 24px 72px; }
.kicker { color: #5f6b76; font-size: 0.85rem; letter-spacing: 0.04em; text-transform: uppercase; margin: 0 0 8px; }
.kicker a { color: inherit; text-decoration: none; }
.kicker a:hover { text-decoration: underline; }
h1 { margin: 0 0 8px; font-size: 1.7rem; line-height: 1.2; }
h2 { margin: 36px 0 12px; font-size: 1.25rem; line-height: 1.3; }
h3 { margin: 28px 0 10px; font-size: 1.05rem; }
h4 { margin: 24px 0 8px; font-size: 0.95rem; }
p, li { color: #3a434c; line-height: 1.55; }
p { margin: 0 0 16px; }
ul, ol { margin: 0 0 16px; padding-left: 24px; }
li { margin: 4px 0; }
a { color: #1a8787; }
hr { border: 0; border-top: 1px solid #e4e7ec; margin: 32px 0; }
code { background: #f2f4f6; border-radius: 4px; padding: 1px 5px; font-size: 0.88em; }
pre { background: #f6f8f9; border: 1px solid #e4e7ec; border-radius: 8px; padding: 14px 16px; overflow-x: auto; }
pre code { background: none; padding: 0; font-size: 0.85rem; line-height: 1.5; }
table { border-collapse: collapse; margin: 0 0 20px; width: 100%; font-size: 0.92rem; }
th, td { border: 1px solid #e4e7ec; padding: 7px 10px; text-align: left; vertical-align: top; }
th { background: #f6f8f9; }
.meta { color: #5f6b76; font-size: 0.9rem; margin: 0 0 4px; }
.chips { margin: 8px 0 0; }
.chip { display: inline-block; background: #f2f4f6; border-radius: 999px; color: #5f6b76; font-size: 0.8rem; padding: 3px 10px; margin: 0 6px 6px 0; }
.hero { border: 1px solid #d7dde3; border-radius: 12px; padding: 22px 24px; margin: 0 0 40px; }
.hero h2 { margin: 4px 0 8px; font-size: 1.3rem; }
.hero a { text-decoration: none; }
.hero a:hover { text-decoration: underline; }
.record { list-style: none; margin: 0 0 8px; padding: 0; border-top: 1px solid #e4e7ec; }
.record li { border-bottom: 1px solid #e4e7ec; margin: 0; }
.record a { display: block; padding: 14px 0; text-decoration: none; }
.record a:hover { text-decoration: underline; }
.record span { color: #5f6b76; display: block; font-size: 0.9rem; margin-top: 4px; }
footer { color: #8a949d; font-size: 0.8rem; margin-top: 56px; border-top: 1px solid #e4e7ec; padding-top: 16px; }
`.trim();

export const generatedNote =
  "<!-- Generated by scripts/build-reports.mjs from packages/review-host/reports-manifest.json. Do not edit by hand; edit the manifest or source and run `just reports-build`. -->";

export function page(title: string, body: string): string {
  return [
    "<!doctype html>",
    '<html lang="en">',
    generatedNote,
    "<head>",
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    '<meta name="robots" content="noindex, nofollow" />',
    `<title>${escapeHtml(title)}</title>`,
    `<style>\n${reportCss}\n</style>`,
    "</head>",
    "<body>",
    "<main>",
    body,
    "</main>",
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

export function chips(report: ReportEntry): string {
  return [`<span class="chip">${escapeHtml(report.kind)}</span>`]
    .concat(
      (report.provenance ?? []).map(
        (provenance) => `<span class="chip">${escapeHtml(provenance)}</span>`,
      ),
    )
    .join("");
}

export function reportHref(report: ReportEntry): string {
  const fileName = report.source.type === "static-html"
    ? basename(report.source.path)
    : `${report.id}.html`;
  return `/reports/${fileName}`;
}
